project_id         = "replace value"
region             = "us-central1"
chain_name         = "replace value"
node_name          = "replace value"
container_command  = "replace value"
docker_image       = "replace value"
project_name       = "replace value"
