---
name: Auto Label


on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write


jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          manifest: .github/labels.yml

      - uses: fuxingloh/multi-labeler@v2.0.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-path: .github/labeler.yml
